version: 0.1

phases:
  install:
    commands:
      - echo Installing Node 14
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
    pre_build:
      commands:
        - echo Installing dependencies
        - npm i
    build:
      commands:
        - echo Testing...
        - npm run test
        - echo Building...
        - npm run build
artifacts:
  files:
    - "**/*"
