version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies
      - npm i
  build:
    commands:
      - echo eslint running...
      - npm run eslint-check
      - echo Testing...
      - npm run test
      - echo Building...
      - npm run build
artifacts:
  files:
    - "./build/**"
